version: '3'
services:
  app:
    container_name: todo
    build: .
    ports: 
      - 5050:5050 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - todo-postgres          
    networks:
      - todo


  todo-postgres:
    image: postgres:latest
    container_name: todo_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - todo
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - todo-postgres
    ports:
      - "8080:80"
    networks:
      - todo
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  todo:
    driver: bridge